# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LunarConsoleAppFull' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LunarConsoleApp
  pod 'CocoaAsyncSocket'

  target 'LunarConsoleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LunarConsoleAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'CocoaAsyncSocket'
  end

end

target 'LunarConsoleAppFree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LunarConsoleAppFree
  pod 'CocoaAsyncSocket'
end
